# -*- coding: utf-8 -*-
"""Sentimental_First.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmFione-KBH7ezVVNCErpLb0c4Tm3qLd
"""

import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

docs = [
    "I loved the movie! It was amazing. 10/ 10 : )",
    "The movie was terrible. Waste of time !!",
    "A masterpiece of storytellying. Would watch again.",
]

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower()
    text = re.sub(rf"[{string.punctuation}]"," ", text)
    text = re.sub(r"\d+", " ", text) #Remove numbers
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(tokens)

preprocessed_docs = [preprocess_text(doc) for doc in docs]

for i , doc in enumerate(preprocessed_docs):
    print(f"Original Document {i+1}: {docs[i]}")
    print(f"Preprocessed Document {i+1}: {doc}")
    print("-" * 50)

from sklearn.feature_extraction.text import CountVectorizer

docs = ["I love programming.", "Programming is fun! ", "I love fun activities."]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

print("Vocabulary: ",vectorizer.get_feature_names_out())
print("Encoded Matrix: \n",X.toarray())