# -*- coding: utf-8 -*-
"""EDA_ Shopping Trends Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQ-VotopPGgbqrRU-8ZnIYqCV7cR7XPr

![](https://i.imgur.com/KhDDHls.gif)
![](https://i.imgur.com/Ffjv44w.gif)

from google.colab import drive
drive.mount('/content/drive')

<div style="color: White; display: fill;
            border-radius: 5px;
            background-color: #123456;
            font-size: 100%;
            font-family: Verdana">

<p style="padding: 7px; color: Black;">
      <ul>  📌 <b>Customer ID</b> - Unique identifier for each customer.<br>
        📌 <b>Age</b> - Age of the customer.<br>
        📌 <b>Gender</b> - Gender of the customer (Male/Female).<br>
        📌 <b>Item Purchased</b> - The item purchased by the customer.<br>
        📌 <b>Category</b> - Category of the item purchased.<br>
        📌 <b>Purchase Amount (USD)</b> - The amount of the purchase in USD.<br>
        📌 <b>Location</b> - Location where the purchase was made.<br>
        📌 <b>Size</b> - Size of the purchased item.<br>
        📌 <b>Color</b> - Color of the purchased item.<br>
        📌 <b>Season</b> - Season during which the purchase was made.<br>
        📌 <b>Review Rating</b> - Rating given by the customer for the purchased item.<br>
        📌 <b>Subscription Status</b> - Indicates if the customer has a subscription (Yes/No).<br>
        📌 <b>Shipping Type</b> - Type of shipping chosen by the customer.<br>
        📌 <b>Discount Applied</b> - Indicates if a discount was applied to the purchase (Yes/No).<br>
        📌 <b>Promo Code Used</b> - Indicates if a promo code was used for the purchase (Yes/No).<br>
        📌 <b>Previous Purchases</b> - Number of previous purchases made by the customer.<br>
        📌 <b>Payment Method</b> - Customer's most preferred payment method.<br>
        📌 <b>Frequency of Purchases</b> - Frequency at which the customer makes purchases (e.g., Weekly, Fortnightly, Monthly).<br><br>
    <p style = "padding: 3px; color: Black;">
"""

!pip install WordCloud

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

""" **This line imports the dataset into a Pandas DataFrame named shop**.

*   pd.read_csv() is a function to read a CSV file into a DataFrame.
*   '/content/shopping_trends_updated.csv' is the path to the CSV file (adjust the path based on your file location).




"""

shop = pd.read_csv('/content/shopping_trends_updated.csv')

""" **Returns the dimensions of the DataFrame**"""

shop.shape

shop.to_excel('/content/shopping_trends_updated.xlsx')

"""**Displays the first 5 rows of the DataFrame by default.**"""

shop.head()

"""**Displays the data type of each column in the DataFrame.**"""

shop.dtypes

"""**Lists all column names in the DataFrame.**"""

shop.columns

"""**Provides a concise summary of the DataFrame.**"""

shop.info()

shop.shape

"""**Checks for missing values in the dataset.**
*   isnull(): Identifies cells with missing values (NaN).
*   sum(): Sums up the number of missing values for each column.
"""

shop.isnull().sum()

print(f"The unique values of the 'Gender' column are: {shop['Gender'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Category' column are: {shop['Category'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Size' column are: {shop['Size'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Subscription Status' column are: {shop['Subscription Status'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Shipping Type' column are: {shop['Shipping Type'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Discount Applied' column are: {shop['Discount Applied'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Promo Code Used' column are: {shop['Promo Code Used'].unique()}")
print()# This will print a blank line
print(f"The unique values of the 'Payment Method' column are: {shop['Payment Method'].unique()}")

"""## OBSERVATION:
Upon initial examination of the dataset, it is evident that we have a comprehensive and well-structured dataset with 3900 rows and 18 columns. The data is complete, with no missing values, which allows us to proceed confidently with our analysis.

Let's delve into the columns and their significance in understanding our custome      

-  **Customer ID:** This column serves as a unique identifier for each customer, enabling us to differentiate between individuals.
-  **Age:** The age column provides insights into the age demographics of our customers, helping us understand their preferences and behaviors.
-  **Gender:** This column showcases the gender of the customers, enabling us to analyze buying patterns based on gender.
-  **Item Purchased:** Here, we can identify the specific products that customers have bought, allowing us to gain an understanding of popular choices.
-  **Category:** The category column categorizes the products into different groups such as clothing, footwear, and more, aiding us in analyzing trends within specific product categories.
-  **Purchase Amount (USD):** This column reveals the amount customers spent on their purchases, providing insights into their spending habits.
-  **Location:** The location column indicates the geographical location of customers, which can help identify regional trends and preferences.
-  **Size:** This column denotes the size of the purchased products, assisting in understanding size preferences across different categories.
-  **Color:** Here, we can determine the color preferences of customers, aiding in analyzing color trends and their impact on purchasing decisions.
-  **Season:** The season column allows us to identify the season during which customers made their purchases, enabling us to explore seasonal shopping trends.
-  **Review Rating:** This column showcases the ratings given by customers, providing valuable feedback on product satisfaction and quality.
-  **Subscription Status:** This column indicates whether customers have opted for a subscription status, which can help us understand customer loyalty and engagement.
-  **Shipping Type:** Here, we can identify the different shipping methods used to deliver products to customers, shedding light on preferred shipping options.
-  **Discount Applied:** This column indicates whether a discount was applied to the purchased products, enabling us to analyze the impact of discounts on customer behavior.
-  **Promo Code Used:** Here, we can identify whether customers utilized promo codes during their purchases, helping us evaluate the effectiveness of promotional campaigns.
-  **Previous Purchases:** This column reveals the number of previous purchases made by customers, aiding in understanding customer loyalty and repeat business.
-  **Payment Method:** The payment method column showcases the various methods used by customers to make their purchases, allowing us to analyze preferred payment options.
-  **Frequency of Purchases:** This column provides insights into the frequency at which customers make purchases, helping us identify patterns and customer buying habits.

ustomer buying habits.
With this rich and diverse dataset, we are well-equipped to explore customer shopping trends, understand their preferences, and uncover valuable insights that can drive informed decision-making and enhance the overall customer experience. Let's embark on this exciting analysis journey!

## 1 What is the overall distribution of customer ages in the dataset?

**This command calculates the frequency of each unique value in the Age column of the shop DataFrame.**
"""

shop['Age'].value_counts()

shop['Age'].mean()

shop['Gender'].unique()

shop['Age_category'] = pd.cut(shop['Age'], bins= [0,15, 18 , 30 , 50 , 70] , labels= ['child' , 'teen' , 'Young Adults' ,'Middle-Aged Adults'
                                                                                             , 'old'] )

"""**Creates a histogram, which is typically used to display the distribution of a numerical variable**
*   shop: The dataset being used (your DataFrame).
*   y='Age': The Age values are plotted on the y-axis

*   x='Age_category': The Age_category is plotted on the x-axis.
"""

fig = px.histogram(shop , y = 'Age' , x = 'Age_category' , color='Gender')
fig.update_layout(
    title="Age Distribution by Category",
    xaxis_title="Age Category",
    yaxis_title="Frequency",
    template="plotly_white"
)
fig.show()

"""**OBSERVATION**

> It seems old age people are most customers. Male customers are more than female customers.

## 2 How does the average purchase amount vary across different product categories?
"""

shop.columns

shop['Category'].unique()

"""**Calculates the average purchase amount for each category.**


"""

avg_purchase = shop.groupby('Category')['Purchase Amount (USD)'].mean().sort_values(ascending=False)
print(avg_purchase)

avg_purchase.plot(kind='bar', x='Category', y='Purchase Amount (USD)', color='orange')
plt.title('Average Purchase Amount by Category')
plt.xlabel('Category')
plt.ylabel('Average Purchase Amount (USD)')
plt.show()

avg_purchase = shop.groupby('Gender')['Purchase Amount (USD)'].mean().sort_values(ascending=False)
print(avg_purchase)

sns.barplot(data=shop, x='Gender', y='Purchase Amount (USD)', errorbar=None)
plt.title('Average Purchase Amount by Gender')
plt.xlabel('Gender')
plt.ylabel('Average Purchase Amount (USD)')
plt.show()

fig, axes = plt.subplots(1, figsize=(12, 5))
sns.barplot(data=shop, x='Gender', y='Purchase Amount (USD)', hue='Category', errorbar=None)
plt.title('Average Purchase Amount by Gender and Category')
plt.xlabel('Gender')
plt.ylabel('Average Purchase Amount (USD)')
plt.legend(title='Category')
plt.show()

"""**OBSERVATION:**

> Average count of footwear is most. Average count of female is more than male.

## 3 Which gender has the highest number of purchases?
"""

shop.columns

"""**Total Count of purchases by Gender**"""

purchase_count = shop['Gender'].value_counts()

sns.barplot(x=purchase_count.index, y=purchase_count.values, hue=purchase_count.index, palette='pastel', legend=False)
plt.title('Number of Purchases by Gender')
plt.xlabel('Gender')
plt.ylabel('Count of Purchases')

for i, count in enumerate(purchase_count.values):
    plt.text(i, count + 2, str(count), ha='center', va='bottom')

plt.show()

purchase_count_by_category = shop['Category'].value_counts()

sns.barplot(x=purchase_count_by_category.index, y=purchase_count_by_category.values, hue=purchase_count_by_category.index, palette='pastel',legend = False)
plt.title('Total Number of Purchases by Category')
plt.xlabel('Category')
plt.ylabel('Total Number of Purchases')

for i, count in enumerate(purchase_count_by_category.values):
    plt.text(i, count + 2, str(count), ha='center', va='bottom')

plt.xticks(rotation=45)
plt.show()

"""**OBSERVATION**:

> Total purchases is greater in clothing. Male purchase is more than female.

## 4 What are the most commonly purchased items in each category?
"""

shop.columns

"""**Count of item purchased in Category**"""

grouped_data = shop.groupby('Category')['Item Purchased'].value_counts()
table_format = grouped_data.reset_index(name='Count')
print(table_format)

table_format.to_csv('category_item_counts.csv', index=False)

"""TABULAR FORMAT"""

from tabulate import tabulate
print(tabulate(table_format, headers='keys', tablefmt='grid'))

fig = px.histogram(shop , x = 'Item Purchased' , color = 'Category')
fig.update_layout(
    title="Commonly purchased item in each category",
    xaxis_title="Item Purchased",
    yaxis_title="Count",
    template="plotly_white"
)
fig.show()

"""**OBSERVATION:**

> Blouse and shirts have most purchase in Clothing category.

> Sandals have most purchase in Footwear category.

> Jacket have most purchase in Outwear category.

> Jewellery have most purchase in Accessories category.

## 5 Are there any specific seasons or months where customer spending is significantly higher?
"""

shop['Season'].unique()

shop[shop['Season'] == 'Summer'].value_counts().sum()

shop[shop['Season'] == 'Winter'].value_counts().sum()

shop[shop['Season'] == 'Spring'].value_counts().sum()

shop[shop['Season'] == 'Fall'].value_counts().sum()

fig = px.histogram(shop , x = 'Season' , range_y= [200 , 1500] )
fig.update_layout(
    title="Total Purchase by Season",
    xaxis_title="Season",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

fig = px.pie(
    shop,
    names='Season',
    title='Distribution of Purchases by Season',
    hole=0.4
)

fig.show()

"""**OBSERVATION:**

> Spring season has most purchages.

## 6 What is the average rating given by customers for each product category?
"""

shop_groupby = shop.groupby('Category')['Review Rating'].mean().reset_index()

fig = px.bar(shop_groupby ,x= 'Category' , y = 'Review Rating', color = 'Category' )
fig.update_layout(
    title="Average Rating by Category",
    xaxis_title="Category",
    yaxis_title="Average Rating",
    template="plotly_white"
)
fig.show()

fig = px.line(
    shop_groupby,
    x='Category',
    y='Review Rating',
    title='Review Ratings by Category',
    markers=True
)
fig.update_layout(
    xaxis_title='Category',
    yaxis_title='Average Review Rating',
    title='Review Ratings by Category',
    template='plotly_dark'
)
fig.show()

"""**OBSERVATION:**

> Footwear has best review rating.

## 7 Are there any notable differences in purchase behavior between subscribed and non-subscribed customers?
"""

shop.columns

shop['Subscription Status'].unique()

subscription_count = shop['Subscription Status'].value_counts()

sns.barplot(x=subscription_count.index, y=subscription_count.values, hue=subscription_count.index, palette='pastel',legend = False)
plt.title('Subscription Purchase Status')
plt.xlabel('Subscription Status')
plt.ylabel('Purchase Amount (USD)')

for i, count in enumerate(subscription_count.values):
    plt.text(i, count + 2, str(count), ha='center', va='bottom')

plt.xticks(rotation=45)
plt.show()

shop['Purchase Amount (USD)'].sum()

shop.groupby('Subscription Status')['Purchase Amount (USD)'].mean()

"""**OBSERVATION:**

> Non Subscription has more purchases than subscription.

## 8 Which payment method is the most popular among customers?
"""

shop.groupby('Payment Method')['Purchase Amount (USD)'].mean().sort_values(ascending= False)

shop_groupby = shop.groupby('Payment Method')['Purchase Amount (USD)'].mean().reset_index()

fig = px.bar(shop_groupby , x = 'Payment Method' , y = 'Purchase Amount (USD)',color = 'Payment Method')
fig.update_layout(
    title="Average Purchase Amount by Payment Method",
    xaxis_title="Payment Method",
    yaxis_title="Average Purchase Amount (USD)",
    template="plotly_white"
)
fig.show()

sns.barplot(shop ,x='Payment Method' , y = 'Purchase Amount (USD)',legend = False)
plt.title('Average Purchase Amount by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Average Purchase Amount (USD)')
plt.show()

sns.scatterplot(data=shop, x='Payment Method', y='Purchase Amount (USD)', color='blue')
plt.title('Average Purchase Amount by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Average Purchase Amount (USD)')
plt.show()

"""**OBSERVATION:**

> Debit Card is mostly the payement method

## 9 Do customers who use promo codes tend to spend more than those who don't?
"""

shop_groupby  = shop.groupby('Promo Code Used')['Purchase Amount (USD)'].sum().reset_index()

fig = px.sunburst(shop , path=['Gender' , 'Promo Code Used'] , values='Purchase Amount (USD)',color = 'Gender')
fig.update_layout(
    title="Total Purchase by Gender and Promo Code Used",
    xaxis_title="Promo Code Used",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

fig  =  px.bar(shop_groupby , x= 'Promo Code Used' , y = 'Purchase Amount (USD)',color = 'Promo Code Used')
fig.update_layout(
    title="Total Purchase by Promo Code Used",
    xaxis_title="Promo Code Used",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

"""**OBSERVATION:**

> Purchases by Promo Code is more, and that done by males only.

## 10 How does the frequency of purchases vary across different age groups?
"""

shop[['Age' , 'Age_category']]

shop['Age_category'].unique()

shop_group = shop.groupby('Frequency of Purchases')['Age'].sum()

grouped_data = shop.groupby(['Frequency of Purchases', 'Age_category'], observed=True)['Age'].count().reset_index()

fig = px.sunburst(
    grouped_data,
    path=['Frequency of Purchases', 'Age_category'],
    values='Age',
    title='Sunburst Chart of Frequency of Purchases by Age Category'
)
fig.show()

fig = px.treemap(
    grouped_data,
    path=['Frequency of Purchases', 'Age_category'],
    values='Age',
    title='Treemap of Frequency of Purchases by Age Category'
)
fig.show()

import warnings

# Suppress warnings
warnings.filterwarnings("ignore", category=FutureWarning)

"""**OBSERVATION:**

> Every 3 month, Monthly , Fortnightly and weekly  => Middle aged Adults has more purchases

> Annually, , Quartely and Bi-weekly  => Old aged has more purchases

## 11 Are there any correlations between the size of the product and the purchase amount?
"""

shop.columns

shop_group = shop.groupby('Size')['Purchase Amount (USD)'].sum().reset_index()

fig  = px.bar(shop_group , x = 'Size' , y ='Purchase Amount (USD)' ,color = 'Size' )
fig.update_layout(
    title="Total Purchase by Size",
    xaxis_title="Size",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

"""**OBSERVATION:**

> Medium Size has more purchases

## 12 Which shipping type is preferred by customers for different product categories?

Shipping Type Table
"""

shop.groupby('Category')['Shipping Type'].value_counts().sort_values(ascending= False)

shop['Shipping_Category'] =shop['Shipping Type'].map({'Express': 0, 'Free Shipping': 1, 'Next Day Air': 2,
                                                       'Standard': 3, '2-Day Shipping': 4, 'Store Pickup': 5})

shop['Category_num'] =shop['Category'].map({'Clothing':1, 'Footwear':2, 'Outerwear':3, 'Accessories':4})

shop['Category'].unique()

""" Group and count shipping types by product category"""

shipping_counts = shop.groupby('Category')['Shipping Type'].value_counts().sort_values(ascending=False)
print(shipping_counts)

shipping_type_mapping = {
    'Express': 0,
    'Free Shipping': 1,
    'Next Day Air': 2,
    'Standard': 3,
    '2-Day Shipping': 4,
    'Store Pickup': 5
}

shop['Shipping_Category'] = shop['Shipping Type'].map(shipping_type_mapping)

category_mapping = {
    'Clothing': 1,
    'Footwear': 2,
    'Outerwear': 3,
    'Accessories': 4
}

shop['Category_num'] = shop['Category'].map(category_mapping)

shipping_summary = shop.groupby(['Category', 'Shipping Type']).size().unstack(fill_value=0)

shipping_summary.plot(kind='bar', stacked=True, figsize=(10, 6), colormap='viridis')

plt.title('Distribution of Shipping Types by Product Category', fontsize=16)
plt.xlabel('Product Category', fontsize=12)
plt.ylabel('Number of Shipments', fontsize=12)
plt.legend(title='Shipping Type', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

heatmap_data = shop.groupby(['Category', 'Shipping Type']).size().unstack(fill_value=0)

plt.figure(figsize=(12, 8))
sns.heatmap(heatmap_data, annot=True, fmt='d', cmap='coolwarm')

plt.title('Heatmap of Shipping Types by Product Category', fontsize=16)
plt.xlabel('Shipping Type', fontsize=12)
plt.ylabel('Product Category', fontsize=12)
plt.tight_layout()
plt.show()

"""**OBSERVATION:**

> Accessories has more purchase by Store Pickup shipping type

> Clothing has more purchase by Standard shipping type

> Footwear has more purchase by Free shipping type

> Outwear has more purchase by Free Shipping type

## 13 How does the presence of a discount affect the purchase decision of customers?
"""

shop.columns

shop_group = shop.groupby('Discount Applied')['Purchase Amount (USD)'].sum().reset_index()

fig = px.histogram(shop_group , x = 'Discount Applied' , y = 'Purchase Amount (USD)', color='Discount Applied')
fig.update_layout(
    title="Total Purchase by Discount Applied",
    xaxis_title="Discount Applied",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

fig = px.sunburst(shop , path = ['Gender' , 'Discount Applied'], values='Purchase Amount (USD)' , color= 'Gender')
fig.update_layout(
    title="Total Purchase by Gender and Discount Applied",
    xaxis_title="Discount Applied",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

"""**OBSERVATION:**

> Discount Applied has about 100k purchases which is good but still less than not discount appled purchases.

> Discount Applied more on purchases by Male.

## 14 Are there any specific colors that are more popular among customers?
"""

fig = px.histogram(shop , x = 'Color', color = 'Color')
fig.update_layout(
    title="Total Purchase by Color",
    xaxis_title="Color",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

shop['Color'].value_counts().nlargest(5)

"""**OBSERVATION:**

> Olive has more purchases than any other colour

## 15 What is the average number of previous purchases made by customers?
"""

shop['Previous Purchases'].mean()

"""Mean value of numeric columns"""

mean_numeric_columns = shop.select_dtypes(include=np.number).mean()

mean_df = pd.DataFrame({'Column': mean_numeric_columns.index, 'Mean': mean_numeric_columns.values})
print(tabulate(mean_df, headers='keys', tablefmt='psql'))

numeric_columns = shop.select_dtypes(include=np.number).columns

mean_values = shop[numeric_columns].mean()

mean_df = pd.DataFrame({'Column': mean_values.index, 'Mean Value': mean_values.values})

mean_values.plot(kind='bar', figsize=(10, 6), color='skyblue')
plt.title('Average Values of Numeric Columns', fontsize=16)
plt.xlabel('Columns', fontsize=12)
plt.ylabel('Average Value', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**OBSERVATION:**

> Previous Purchases has mean value 25.35

> Purchase Amount has mean value 59.76

# 16 How does the purchase amount differ based on the review ratings given by customers?

Review Rating and Purchase Amount
"""

rating_analysis = shop.groupby('Review Rating')['Purchase Amount (USD)'].mean().reset_index()
print(rating_analysis)

plt.figure(figsize=(10, 6))
sns.barplot(x='Review Rating', y='Purchase Amount (USD)', data=rating_analysis, palette='viridis')
plt.title('Average Purchase Amount by Review Rating', fontsize=16)
plt.xlabel('Review Rating', fontsize=12)
plt.ylabel('Average Purchase Amount', fontsize=12)
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x='Review Rating', y='Purchase Amount (USD)', data=shop, palette='coolwarm')
plt.title('Purchase Amount Distribution by Review Rating', fontsize=16)
plt.xlabel('Review Rating', fontsize=12)
plt.ylabel('Purchase Amount (USD)', fontsize=12)
plt.show()

"""**OBSERVATION:**

> Rating 5.0 has highest purchase amount

## 17 Are there any noticeable differences in purchase behavior between different locations?

Location and Purchase Amount
"""

shop.groupby('Location')['Purchase Amount (USD)'].mean().sort_values(ascending = False)

shop_group = shop.groupby('Location')['Purchase Amount (USD)'].mean().reset_index()

fig = px.bar(shop_group, x = 'Location' , y = 'Purchase Amount (USD)',color='Location')
fig.update_layout(
    title="Total Purchase by Location",
    xaxis_title="Location",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

"""**OBSERVATION:**

> Alaska has most purchases

# 18 Is there a relationship between customer age and the category of products they purchase?
"""

shop_group = shop.groupby('Category')['Age'].mean().reset_index()

fig = px.bar(shop_group ,y = 'Age' , x= 'Category',color = 'Category')
fig.update_layout(
    title="Average Age by Category",
    xaxis_title="Category",
    yaxis_title="Average Age",
    template="plotly_white"
)
fig.show()

"""OBSERVATION:

> Average age is between 40 and 45 for purchases for each category

## 19 How does the average purchase amount differ between male and female customers?
"""

shop_group = shop.groupby('Gender')['Purchase Amount (USD)'].sum().reset_index()

fig = px.bar(shop_group , x = 'Gender' , y = 'Purchase Amount (USD)', color = 'Gender')
fig.update_layout(
    title="Total Purchase by Gender",
    xaxis_title="Gender",
    yaxis_title="Total Purchase",
    template="plotly_white"
)
fig.show()

px.sunburst(data_frame= shop , path = ['Gender' ,'Age_category'] , values='Purchase Amount (USD)')

"""OBSERVATION:

>Female has about half the purchase amount than male

>In Male, Middle Aged Adults has more purchases

> In Female , Middle aged Adults has more purchases

# 20 How does the number of previous purchases correlate with spending?
"""

sns.scatterplot(
    x=shop['Previous Purchases'],
    y=shop['Purchase Amount (USD)'],
    hue=shop['Category'],
    palette="viridis"
)

plt.title('Spending vs. Previous Purchases', fontsize=16)
plt.xlabel('Number of Previous Purchases', fontsize=12)
plt.ylabel('Purchase Amount (USD)', fontsize=12)
plt.legend(title='Category', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""**OBSERVATION:**

>Gradual increase in spending is noticeable with an increasing number of previous purchases, indicating a loyalty effect where frequent customers spend more.


"""